### ISSUE TITLE
Investigate failure to ingest super large SBOM

### ISSUE THREAD

**Issue by lulf** [trustification/trustification#161]
To AWS s3 specifically, with OpenShift SBOM.

**Comment by jcrossley3** [comment]
I guess I need to bite the bullet and figure out how to test against actual S3. Any tips?

**Comment by jcrossley3** [comment]
I've confirmed that this occurs when the `rust-s3` crate uses the AWS multipart upload feature. User-defined metadata is sent via the `with_extra_headers` method of the `Bucket` struct. Any requests created with that bucket will send all the extra headers. In the case of a multipart upload, a number of related requests are sent, e.g. `initiate`, `send-part`, and ultimately `complete` (or `abort`). The `rust-s3` crate sends those extra metadata headers, but AWS only expects those headers in the `initiate` request. So the first `send-part` fails with an `InvalidArgument` due to the presence of that `x-amz-meta-...` header.

In our case, we're only sending a version (currently hardcoded to `1`) that is never used. So I confirmed a quick workaround would be to just stop sending that. :)

I'll inquire of the `rust-s3` team whether they have a bug or I'm using their API wrong.
