### ISSUE TITLE
[Bombastic] Chunked/streaming API

### ISSUE THREAD

**Issue by lulf** [trustification/trustification#21]
SBOMs can be as large as 300 MB in the case of OpenShift. The HTTP API should be refactored to support chunking the body so that we don't have to hold the entire body in memory on upload.

**Comment by jcrossley3** [comment]
i think i can preserve existing behavior -- `Object.data` will remain `Vec[u8]`, but if it's empty, that'll mean the data is actually at a different path, e.g. `/sbom` prefix instead of `/data` in the bucket. this will happen when a POST is made with `Transfer-Encoding: chunked`, in which case the now-optional query params will be required (because i'm going to defer parsing a partial doc to determine them). now i just need to figure out how to adapt AsyncRead (rust_s3 crate) types to Stream (actix crate) and back
