### ISSUE TITLE
Expectations: searching for Vex/Vulnerabilities

### ISSUE THREAD

**Issue by ctron** [trustification/trustification#235]
Trying for gather my expectations towards searching through CSAF documents.

* [x] There is an "aggregated" (per CSAF document) severity, we seem to store this in the index, but neither are able to search for it, not transport it back to the frontend.
* [x] Searching for a CVE ID turns up all kinds of advisories, it feels like we should have a view structured around CVE ID
* [x] There was a request to be able to search "by product", we should make that possible somehow
* [x] Partial search for cpe

**Comment by lulf** [comment]
> Trying for gather my expectations towards searching through CSAF documents.
> 
> * [ ]  There is an "aggregated" (per CSAF document) severity, we seem to store this in the index, but neither are able to search for it, not transport it back to the frontend.

Agreed, makes sense to add this.

> * [ ]  Searching for a CVE ID turns up all kinds of advisories, it feels like we should have a view structured around CVE ID

That is because a CVE can be part of multiple advisories and part of each doc. I'm not sure what should change in the search backend though. I think spog-api/spog-model should probably restructure the data and return the desired view. (might need to use a higher max limit on the results to make sure you get all advisories).

> * [ ]  There was a request to be able to search "by product", we should make that possible somehow

You can search for 'affected:mycpe' or 'fixed:mycpe', or 'package:mycpe' already (using package might be wrong, its more product id).
