### ISSUE TITLE
invalid_bzip2_encoded integration test fails on AWS

### ISSUE THREAD

**Issue by lulf** [trustification/trustification#691]
On AWS the response code is 201 and not 400, so this is likely to be a difference with MinIO. Disabling the test for now so we can keep CD pipeline running.

**Comment by jcrossley3** [comment]
It's due to [this configuration](https://github.com/trustification/trustification/blob/131a08597dab46ac674c605141d7ffb590894b2f/integration-tests/src/bom.rs#L220), which will be `Validator::None` on a live system.

We could add `--validator sbom` to the bombastic api server deployment. It should effectively be a no-op since the walkers scrub invalid data anyway, but it will cause every SBOM to be loaded into memory. We sort of agreed that would be ok in light of stricter authz creds.

If you'd rather, I could also adjust the tests, so that the test would be ignored conditionally.
